version: 2.1

# Define the jobs we want to run for this project
jobs:
  pull-and-build:
    docker:
      - image: node:latest
    environment:
          CI: false
          NODE_ENV: production
    working_directory: ./packages/solsantas/
    steps:
      - checkout
      - run: apt-get update && apt-get -y install rsync
      - run: cp .env.development .env
      - run: npm install
      - run: npm run build
      - run: rsync -e "ssh -o StrictHostKeyChecking=no" -va ./packages/solsantas/build/ $USER@$IP:/var/www/solsantas.xyz/html/
  build-dev:
    docker:
      - image: node:latest
    environment:
          CI: false
          NODE_ENV: development
    working_directory: ./packages/solsantas/
    steps:
      - checkout
      - run: apt-get update && apt-get -y install rsync
      - run: cd ./packages/solsantas/
      - run: cp .env.development .env
      - run: npm install
      - run: npm run build
      - run: rsync -e "ssh -o StrictHostKeyChecking=no" -va ./packages/solsantas/build/ $USER@$IP:/var/www/dev.solsantas.xyz/html/

# Orchestrate our job run sequence
workflows:
  version: 2
  build-project:
    jobs:
      - pull-and-build:
          filters:
            branches:
              only:
                - master
      - build-dev:
          filters:
              branches:
                only:
                  - dev