version: 2.1

# Define the jobs we want to run for this project
jobs:
  pull-and-build:
    docker:
      - image: arvindr226/alpine-ssh
    environment:
          CI: false
          REACT_APP_CANDY_MACHINE_ID: ExCUMgZXvEG22XhbkN1pTnPnzEi7NQoFrRNuTbExFy29
          REACT_APP_SOLANA_RPC_HOST: https://explorer-api.devnet.solana.com
          REACT_APP_SOLANA_NETWORK: devnet
          REACT_APP_CANDY_START_DATE: 12/25/2021
    steps:
      - checkout
      - run: ssh -oStrictHostKeyChecking=no -v $USER@$IP "./solsantas/.circleci/deploy.sh"
  build-dev:
    docker:
      - image: node:latest
    environment:
          CI: false
          REACT_APP_CANDY_MACHINE_ID: ExCUMgZXvEG22XhbkN1pTnPnzEi7NQoFrRNuTbExFy29
          REACT_APP_SOLANA_RPC_HOST: https://explorer-api.devnet.solana.com
          REACT_APP_SOLANA_NETWORK: devnet
          REACT_APP_CANDY_START_DATE: 12/25/2021
    steps:
      - checkout
      - run: apt-get update && apt-get -y install rsync
      - run: cd ./packages/solsantas/ && npm install
      - run: cd ./packages/solsantas/ && npm run build
      - run: rsync -e "ssh -o StrictHostKeyChecking=no" -va ./packages/solsantas/build/ $USER@$IP:/var/www/dev.solsantas.xyz/html/

# Orchestrate our job run sequence
workflows:
  version: 2
  build-project:
    jobs:
      - pull-and-build:
          filters:
            branches:
              only:
                - master
      - build-dev:
          filters:
              branches:
                only:
                  - dev