version: 2.1

# Define the jobs we want to run for this project
jobs:
  pull-and-build:
    docker:
      - image: arvindr226/alpine-ssh
    steps:
      - checkout
      - run: ssh -oStrictHostKeyChecking=no -v $USER@$IP "./solsantas/.circleci/deploy.sh"
  build-dev:
    docker:
      - image: node:latest
    steps:
      - checkout
      - run: apt-get update && sudo apt-get install rsync
      - run: npm install
      - run: npm run build
      - run: rsync -va ./packages/solsantas/build/ $USER@$IP:/var/www/dev.solsantas.xyz/html/

# Orchestrate our job run sequence
workflows:
  version: 2
  build-project:
    jobs:
      - pull-and-build:
          filters:
            branches:
              only:
                - master
      - build-dev:
          filters:
              branches:
                only:
                  - dev