[programs.localnet]
anchor_escrow = "DM3FhshMv4p33HhiNMnM7ofgaJVNaibzbNZyUNT9whAt"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "https://api.devnet.solana.com"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
