[programs.mainnet]
anchor_escrow = "2xVYRiEK9vr6cdyM1wjpEGJvGjQdMysXUy7q62vNs2rd"

[programs.localnet]
anchor_escrow = "C4jvtoUqUoSTsbYLNtTKY9vTtHpJLKpALyC1oDKGZTdZ"

[programs.devnet]
anchor_escrow = "C4jvtoUqUoSTsbYLNtTKY9vTtHpJLKpALyC1oDKGZTdZ"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "https://api.devnet.solana.com"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
